package generator

import (
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/si-generator/pkg/model"
	"gopkg.in/yaml.v3"
)

// Writer handles writing SecurityInsights to YAML files
type Writer struct {
	verbose bool
}

// NewWriter creates a new Writer instance
func NewWriter(verbose bool) *Writer {
	return &Writer{verbose: verbose}
}

// WriteOptions configures write behavior
type WriteOptions struct {
	DryRun    bool
	Force     bool
	ShowEmpty bool
}

// Write writes SecurityInsights to the specified output path
func (w *Writer) Write(insights model.SecurityInsights, outputPath string, opts WriteOptions) error {
	var content []byte
	var err error

	if opts.ShowEmpty {
		content, err = w.ToYAMLWithEmpty(insights)
	} else {
		content, err = w.ToYAML(insights)
	}
	if err != nil {
		return fmt.Errorf("failed to generate YAML: %w", err)
	}

	if opts.DryRun {
		fmt.Println(string(content))
		return nil
	}

	if _, err := os.Stat(outputPath); err == nil && !opts.Force {
		return fmt.Errorf("file %s already exists, use --force to overwrite", outputPath)
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(outputPath, content, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", outputPath, err)
	}

	if w.verbose {
		fmt.Printf("Successfully wrote security-insights.yml to %s\n", outputPath)
	}

	return nil
}

// WriteToWriter writes SecurityInsights to an io.Writer
func (w *Writer) WriteToWriter(insights model.SecurityInsights, writer io.Writer) error {
	content, err := w.ToYAML(insights)
	if err != nil {
		return fmt.Errorf("failed to generate YAML: %w", err)
	}

	_, err = writer.Write(content)
	return err
}

// ToYAML converts SecurityInsights to YAML bytes
func (w *Writer) ToYAML(insights model.SecurityInsights) ([]byte, error) {
	header := []byte("# Security Insights Configuration\n# Generated by si-generator\n# Schema: https://github.com/ossf/security-insights-spec/blob/main/specification.md\n\n")

	content, err := yaml.Marshal(insights)
	if err != nil {
		return nil, err
	}

	return append(header, content...), nil
}

// ToYAMLWithEmpty converts SecurityInsights to YAML bytes, showing all fields including empty ones
func (w *Writer) ToYAMLWithEmpty(insights model.SecurityInsights) ([]byte, error) {
	header := []byte("# Security Insights Configuration\n# Generated by si-generator\n# Schema: https://github.com/ossf/security-insights-spec/blob/main/specification.md\n\n")

	// Ensure all nested structs are initialized so they appear in output
	expanded := expandInsights(insights)

	content, err := yaml.Marshal(expanded)
	if err != nil {
		return nil, err
	}

	return append(header, content...), nil
}

// expandInsights ensures all nested structures are initialized for full output
func expandInsights(insights model.SecurityInsights) model.SecurityInsights {
	// Ensure Project exists
	if insights.Project == nil {
		insights.Project = &model.Project{}
	}
	if insights.Project.Steward == nil {
		insights.Project.Steward = &model.Steward{}
	}
	if insights.Project.Documentation == nil {
		insights.Project.Documentation = &model.ProjectDocumentation{}
	}
	if insights.Project.VulnerabilityReporting == nil {
		insights.Project.VulnerabilityReporting = &model.VulnerabilityReporting{}
	}
	if insights.Project.VulnerabilityReporting.Contact == nil {
		insights.Project.VulnerabilityReporting.Contact = &model.Contact{}
	}

	// Ensure Repository exists
	if insights.Repository == nil {
		insights.Repository = &model.Repository{}
	}
	if insights.Repository.Documentation == nil {
		insights.Repository.Documentation = &model.RepositoryDocumentation{}
	}
	if insights.Repository.License == nil {
		insights.Repository.License = &model.License{}
	}
	if insights.Repository.Release == nil {
		insights.Repository.Release = &model.Release{}
	}
	if insights.Repository.Security == nil {
		insights.Repository.Security = &model.Security{}
	}
	if insights.Repository.Security.Practices == nil {
		insights.Repository.Security.Practices = &model.SecurityPractices{}
	}
	if insights.Repository.Security.Assessments == nil {
		insights.Repository.Security.Assessments = &model.Assessments{}
	}

	return insights
}

// ToYAMLString converts SecurityInsights to a YAML string
func (w *Writer) ToYAMLString(insights model.SecurityInsights) (string, error) {
	content, err := w.ToYAML(insights)
	if err != nil {
		return "", err
	}
	return string(content), nil
}

// ReadExisting reads an existing security-insights.yml file
func ReadExisting(path string) (*model.SecurityInsights, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("failed to read file: %w", err)
	}

	var insights model.SecurityInsights
	if err := yaml.Unmarshal(content, &insights); err != nil {
		return nil, fmt.Errorf("failed to parse YAML: %w", err)
	}

	return &insights, nil
}
