package generator

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/vinayada1/si-tool/pkg/model"
	"gopkg.in/yaml.v3"
)

// Writer handles writing SecurityInsights to YAML files
type Writer struct {
	verbose bool
}

// NewWriter creates a new Writer instance
func NewWriter(verbose bool) *Writer {
	return &Writer{verbose: verbose}
}

// WriteOptions configures write behavior
type WriteOptions struct {
	DryRun bool
	Force  bool
}

// Write writes SecurityInsights to the specified output path
func (w *Writer) Write(insights model.SecurityInsights, outputPath string, opts WriteOptions) error {
	content, err := w.ToYAML(insights)
	if err != nil {
		return fmt.Errorf("failed to generate YAML: %w", err)
	}

	if opts.DryRun {
		fmt.Println(string(content))
		return nil
	}

	if _, err := os.Stat(outputPath); err == nil && !opts.Force {
		return fmt.Errorf("file %s already exists, use --force to overwrite", outputPath)
	}

	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(outputPath, content, 0644); err != nil {
		return fmt.Errorf("failed to write file %s: %w", outputPath, err)
	}

	if w.verbose {
		fmt.Printf("Successfully wrote security-insights.yml to %s\n", outputPath)
	}

	return nil
}

// ToYAML converts SecurityInsights to YAML bytes
func (w *Writer) ToYAML(insights model.SecurityInsights) ([]byte, error) {
	header := []byte("# Security Insights Configuration\n# Generated by si-generator\n# Schema: https://github.com/ossf/security-insights-spec/blob/main/specification.md\n\n")

	content, err := yaml.Marshal(insights)
	if err != nil {
		return nil, err
	}

	return append(header, content...), nil
}
